ALTER TABLE "agent_runs" DROP CONSTRAINT "agent_runs_user_id_users_id_fk", ADD CONSTRAINT "agent_runs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_runs" DROP CONSTRAINT "agent_runs_session_id_sessions_id_fk", ADD CONSTRAINT "agent_runs_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_runs" DROP CONSTRAINT "agent_runs_attempt_id_attempts_id_fk", ADD CONSTRAINT "agent_runs_attempt_id_attempts_id_fk" FOREIGN KEY ("attempt_id") REFERENCES "public"."attempts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attempts" DROP CONSTRAINT "attempts_question_id_questions_id_fk", ADD CONSTRAINT "attempts_question_id_questions_id_fk" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attempts" DROP CONSTRAINT "attempts_user_id_users_id_fk", ADD CONSTRAINT "attempts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "challenge_artifacts" DROP CONSTRAINT "challenge_artifacts_user_id_users_id_fk", ADD CONSTRAINT "challenge_artifacts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_checkpoints" DROP CONSTRAINT "session_checkpoints_user_id_users_id_fk", ADD CONSTRAINT "session_checkpoints_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspace_snapshots" DROP CONSTRAINT "workspace_snapshots_user_id_users_id_fk", ADD CONSTRAINT "workspace_snapshots_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspace_snapshots" DROP CONSTRAINT "workspace_snapshots_session_id_sessions_id_fk", ADD CONSTRAINT "workspace_snapshots_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;
