import { useEffect, useMemo, useState } from "react";
import Editor from "@monaco-editor/react";
import { ArrowsClockwise, Brain, CaretRight, Check, Clock, Code, Command, Gear, GithubLogo, Graph, House, ListChecks, MagnifyingGlass, Moon, Play, Plus, SidebarSimple, Sparkle, SquaresFour, TerminalWindow, UserCircle, X } from "@phosphor-icons/react";
import type { SessionSummary } from "@pracai/domain";
import type { BootstrapData, PracticeApi } from "../shared/api";
import { browserDemoApi } from "./demo";
import { Button } from "@/components/ui/button";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Textarea } from "@/components/ui/textarea";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import { Command as CommandRoot, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList, CommandShortcut } from "@/components/ui/command";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/animate-ui/components/radix/dialog";
import { ArrowRightIcon, HistoryIcon, HouseIcon, LayoutGridIcon, NetworkIcon, SettingsIcon, SparklesIcon } from "lucide-react";

type Page = "home" | "sessions" | "ability" | "history" | "settings" | "workspace";
const api: PracticeApi = window.practice ?? browserDemoApi();

export function App() {
  const [data, setData] = useState<BootstrapData | null>(null); const [page, setPage] = useState<Page>("home"); const [active, setActive] = useState<SessionSummary | null>(null); const [newSession, setNewSession] = useState(false); const [palette, setPalette] = useState(false);
  useEffect(() => { void api.bootstrap().then(setData); const keyboard = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.shiftKey && event.key.toLowerCase() === "p") { event.preventDefault(); setPalette(true); } if ((event.metaKey || event.ctrlKey) && event.key === "n") { event.preventDefault(); setNewSession(true); } }; addEventListener("keydown", keyboard); return () => removeEventListener("keydown", keyboard); }, []);
  if (!data) return <div className="loading"><span className="spinner"/>Restoring your training state…</div>;
  if (!data.account) return <Auth onStarted={() => {}}/>;
  const open = (session: SessionSummary) => { setActive(session); setPage("workspace"); };
  return <div className="app-shell">
    <Sidebar page={page} onPage={setPage} account={data.account}/>
    <main className="main"><Titlebar page={page} sync={data.syncState} onPalette={() => setPalette(true)} />
      <div className={`content ${page === "workspace" ? "workspace-content" : ""}`}>
        {page === "home" && <Dashboard sessions={data.sessions} onOpen={open} onNew={() => setNewSession(true)}/>} 
        {page === "sessions" && <Sessions sessions={data.sessions} onOpen={open}/>} 
        {page === "ability" && <AbilityMap/>}{page === "history" && <History/>}{page === "settings" && <Settings/>}
        {page === "workspace" && active && <Workspace session={active}/>} 
      </div>
    </main>
    {newSession && <NewSession onClose={() => setNewSession(false)} onCreate={async (goal) => { const result = await api.createSession({ goal }); setNewSession(false); setActive({ ...data.sessions[0]!, id: result.sessionId, title: goal, originalGoal: goal, objective: "Investigating your history…", status: "planning", currentFocus: [], completedQuestions: 0, activeQuestion: null, questionTitles: [], totalSeconds: 0, updatedAt: new Date().toISOString() }); setPage("workspace"); }}/>} 
    {palette && <CommandPalette onClose={() => setPalette(false)} onPage={(value) => { setPage(value); setPalette(false); }}/>} 
  </div>;
}

function Auth({ onStarted }: { onStarted(): void }) { const [email, setEmail] = useState(""); return <div className="auth"><div className="auth-drag"/><section className="auth-panel"><div className="mark"><Code weight="bold"/></div><h1>Train how you think.</h1><p>Adaptive coding sessions built from evidence, not a question queue.</p><label>Email address<input value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" type="email"/></label><button className="primary wide" onClick={() => void api.startAuth("email", email).then(onStarted)}>Continue with email</button><div className="divider"><span>or</span></div><button className="provider" onClick={() => void api.startAuth("google")}><span className="google">G</span>Continue with Google</button><button className="provider" onClick={() => void api.startAuth("github")}><GithubLogo weight="fill"/>Continue with GitHub</button><small>By continuing, you agree that your learning history is private to your account.</small></section><aside className="auth-story"><div className="story-card"><span className="eyebrow">YOUR NEXT SESSION</span><h2>Not another random problem.</h2><div className="target"><b>Training target</b><span>Restoring a sliding-window invariant when several conditions change</span></div><div className="evidence"><Check/> Built from 3 prior attempts</div><div className="evidence"><Check/> Avoids unrelated parsing difficulty</div><div className="evidence"><Check/> Tests transfer, not memorization</div></div></aside></div>; }

function Sidebar({ page, onPage, account }: { page: Page; onPage(p: Page): void; account: NonNullable<BootstrapData["account"]> }) { const items: Array<[Page, string, typeof House]> = [["home", "Home", House], ["sessions", "Sessions", SquaresFour], ["ability", "Ability Map", Graph], ["history", "History", Clock], ["settings", "Settings", Gear]]; return <aside className="sidebar"><div className="traffic-space"/><div className="brand"><span className="brand-mark"><Code weight="bold"/></span><span>Practice AI</span></div><nav>{items.map(([id, label, Icon]) => <button key={id} className={page === id ? "selected" : ""} onClick={() => onPage(id)}><Icon weight={page === id ? "fill" : "regular"}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><div className="mini-streak"><Sparkle weight="fill"/><span><b>4 day streak</b><small>Keep the signal fresh</small></span></div><button className="account"><span>{account.displayName[0]}</span><div><b>{account.displayName}</b><small>{account.email}</small></div><CaretRight/></button></div></aside>; }

function Titlebar({ page, sync, onPalette }: { page: Page; sync: string; onPalette(): void }) { return <header className="titlebar"><span className="page-name">{page === "workspace" ? "Deep JavaScript Runtime" : page === "ability" ? "Ability Map" : title(page)}</span><div className="title-actions"><span className="sync"><span/> {sync === "synced" ? "All changes saved" : sync}</span><button className="command-button" onClick={onPalette}><MagnifyingGlass/>Search or command <kbd>⌘⇧P</kbd></button><button className="icon-button"><SidebarSimple/></button></div></header>; }

function Dashboard({ sessions, onOpen, onNew }: { sessions: SessionSummary[]; onOpen(s: SessionSummary): void; onNew(): void }) { return <div className="page dashboard"><section className="welcome"><div><span className="eyebrow">FRIDAY, JULY 31</span><h1>Ready to sharpen the edges?</h1><p>Your recent attempts point to async ownership as the highest-value next step.</p></div><button className="primary" onClick={onNew}><Plus weight="bold"/>New session</button></section><section className="focus-strip"><div className="focus-icon"><Brain weight="duotone"/></div><div><span className="eyebrow">RECOMMENDED FOCUS</span><h3>Async state ownership</h3><p>Two recent solutions passed but relied on fragile closure timing. A transfer task would clarify whether the model is stable.</p></div><button>Start focused session <CaretRight/></button></section><SectionHeader title="Continue learning" action="View all sessions"/><div className="session-grid">{sessions.map((s) => <SessionCard key={s.id} session={s} onOpen={() => onOpen(s)}/>)}</div><div className="lower-grid"><section><SectionHeader title="Ability movement" action="Open ability map"/><div className="movement-list"><Movement title="Promise orchestration" status="Independent" detail="Confirmed across 4 contexts" tone="green"/><Movement title="Reference ownership" status="Developing" detail="Evidence strengthened today" tone="blue"/><Movement title="Event-loop ordering" status="Uncertain" detail="Best next evidence identified" tone="amber"/></div></section><section><SectionHeader title="This week"/><div className="week"><div><b>6</b><span>questions</span></div><div><b>4h 18m</b><span>focused time</span></div><div><b>73%</b><span>without hints</span></div><div className="bars">{[35,62,42,78,90,54,18].map((h,i)=><span key={i} style={{height:`${h}%`}}/> )}</div></div></section></div></div>; }

function SessionCard({ session, onOpen }: { session: SessionSummary; onOpen(): void }) { return <article className="session-card" onClick={onOpen}><div className="card-top"><span className="status-dot"/><span className="session-status">{session.status}</span><span className="last-active">2 hours ago</span></div><h2>{session.title}</h2><p className="goal">{session.originalGoal}</p><div className="improving"><small>IMPROVING</small><p>{session.currentFocus.join(" · ") || "Establishing your first target"}</p></div><ol className="question-list">{session.questionTitles.map((q, index) => <li key={q.id} className={q.status}><span>{q.status === "completed" ? <Check weight="bold"/> : q.status === "active" ? <span className="pulse"/> : index + 1}</span>{q.title}</li>)}<li className="future"><span/>Next question generated from this attempt</li></ol><footer><span><Clock/> {formatDuration(session.totalSeconds)}</span><button>{session.status === "completed" ? "Review" : "Resume"}<CaretRight weight="bold"/></button></footer></article>; }

function Sessions({ sessions, onOpen }: { sessions: SessionSummary[]; onOpen(s: SessionSummary): void }) { return <div className="page"><div className="page-heading"><div><h1>Sessions</h1><p>Durable learning journeys that adapt after every attempt.</p></div><div className="segmented"><button className="active">Active</button><button>Completed</button><button>All</button></div></div><div className="session-list">{sessions.map((s) => <SessionCard key={s.id} session={s} onOpen={() => onOpen(s)}/>)}</div></div>; }

function Workspace({ session }: { session: SessionSummary }) { const [tab, setTab] = useState("src/queue.ts"); const [code, setCode] = useState(`type Task = () => Promise<void>;

export class EventQueue {
  private pending: Task[] = [];
  private running = false;

  enqueue(task: Task) {
    this.pending.push(task);
    if (!this.running) this.drain();
  }

  private async drain() {
    this.running = true;
    if (this.pending.length > 0) {
      const task = this.pending.shift()!;
      await task();
      this.drain();
    }
    this.running = false;
  }
}`); const [agentOpen, setAgentOpen] = useState(true); return <div className="workspace"><div className="workspace-toolbar"><div><span className="crumb">Question 3 of adaptive session</span><b>Event Queue Repair</b></div><div><span className="timer"><Clock/> 18:42</span><button className="secondary"><Play weight="fill"/>Run tests</button><button className="primary">Submit</button></div></div><div className="workspace-body"><aside className="files"><div className="panel-label">EXPLORER</div><div className="folder">⌄ event-queue</div>{["README.md","src/queue.ts","src/types.ts","tests/queue.test.ts","package.json"].map(f=><button key={f} className={tab===f?"active":""} onClick={()=>setTab(f)}><Code/>{f}</button>)}</aside><section className="editor-pane"><div className="tabs"><button className="active"><Code/>queue.ts<span>●</span></button></div><Editor height="100%" language="typescript" theme="vs-dark" value={code} onChange={(v)=>setCode(v ?? "")} options={{fontSize:13,fontFamily:"SFMono-Regular, Menlo, monospace",minimap:{enabled:false},padding:{top:16},scrollBeyondLastLine:false,renderLineHighlight:"gutter",smoothScrolling:true}}/></section>{agentOpen && <aside className="agent-panel"><div className="agent-head"><div><Brain weight="duotone"/><span><b>Training Agent</b><small>Observing this attempt</small></span></div><button onClick={()=>setAgentOpen(false)}><X/></button></div><div className="target-box"><small>TRAINING TARGET</small><b>Async state ownership</b><p>Show that queue ownership remains valid while newly enqueued work changes the pending set.</p><span>Avoiding: unfamiliar APIs</span></div><div className="conversation"><div className="agent-message"><span className="agent-avatar"><Sparkle weight="fill"/></span><p>I’m watching how you reason about the queue invariant. Run your own tests whenever useful—I’ll stay out of the way unless the evidence suggests a well-timed question.</p></div><div className="timeline-mini"><span/><div><b>You opened queue.ts</b><small>12 minutes ago</small></div></div><div className="timeline-mini"><span/><div><b>Visible tests: 3 of 4</b><small>One ordering case fails</small></div></div></div><div className="remark"><label>Learner remark</label><textarea placeholder="What are you thinking or uncertain about?"/><button>Attach to attempt</button></div></aside>}</div><div className="bottom-panel"><div className="bottom-tabs"><button className="active">Terminal</button><button>Tests <span className="badge">1</span></button><button>Attempt timeline</button></div><pre><span className="muted">practice-ai event-queue %</span> pnpm test{"\n"}<span className="pass">✓ preserves FIFO ordering</span>{"\n"}<span className="pass">✓ waits for async tasks</span>{"\n"}<span className="fail">✗ drains tasks enqueued during completion</span>{"\n"}<span className="muted">  Expected: [A, B, C]  Received: [A, B]</span></pre></div></div>; }

function AbilityMap() { const nodes = [{name:"Async ownership",x:48,y:38,s:"developing"},{name:"Promises",x:27,y:24,s:"independent"},{name:"Event loop",x:71,y:23,s:"uncertain"},{name:"References",x:25,y:64,s:"independent"},{name:"Mutation",x:54,y:72,s:"developing"},{name:"Queues",x:79,y:61,s:"stale"}]; return <div className="page"><div className="page-heading"><div><h1>Ability Map</h1><p>Evidence-backed understanding—not a leaderboard score.</p></div><button className="secondary"><ArrowsClockwise/>Review stale abilities</button></div><div className="ability-layout"><section className="graph-panel">{nodes.map(n=><button className={`graph-node ${n.s}`} style={{left:`${n.x}%`,top:`${n.y}%`}} key={n.name}><span/>{n.name}<small>{n.s}</small></button>)}<svg><line x1="27%" y1="24%" x2="48%" y2="38%"/><line x1="71%" y1="23%" x2="48%" y2="38%"/><line x1="25%" y1="64%" x2="54%" y2="72%"/><line x1="48%" y1="38%" x2="79%" y2="61%"/></svg></section><aside className="ability-detail"><span className="eyebrow">DEVELOPING</span><h2>Async ownership</h2><p>The learner handles direct promise chains but is less consistent when ownership crosses callbacks or mutable queues.</p><h4>Current evidence</h4><ul><li><Check/>Promise Relay solved independently</li><li><Check/>Recognized a stale closure in review</li><li className="warn">● Queue drain invariant remains uncertain</li></ul><h4>Best next evidence</h4><p>Use an event-driven module where new work arrives during an awaited operation.</p><button className="primary">Practise this ability</button></aside></div></div>; }

function History() { return <div className="page"><div className="page-heading"><div><h1>History</h1><p>A complete, replayable record of your learning evidence.</p></div><button className="secondary">Export learner model</button></div><div className="history-list"><HistoryRow icon="JS" title="Event Queue Repair" session="Deep JavaScript Runtime" status="In progress" time="Today · 18 min"/><HistoryRow icon="TS" title="Promise Relay" session="Deep JavaScript Runtime" status="Passed independently" time="Today · 31 min"/><HistoryRow icon="JS" title="Shared Configuration" session="Deep JavaScript Runtime" status="Passed with one hint" time="Yesterday · 24 min"/></div></div>; }

function Settings() { const [mode,setMode]=useState("system"); const changeTheme=(value:string)=>{if(!value)return;setMode(value);document.documentElement.classList.toggle("dark",value==="dark"||(value==="system"&&matchMedia("(prefers-color-scheme: dark)").matches));}; return <div className="page settings"><div className="page-heading"><div><h1>Settings</h1><p>Application, execution, provider, and privacy controls.</p></div></div><section><h3>Appearance</h3><div className="setting-row"><div><b>Theme</b><p>Follow macOS or choose a fixed appearance.</p></div><ToggleGroup type="single" value={mode} onValueChange={changeTheme} variant="outline" size="sm"><ToggleGroupItem value="system">System</ToggleGroupItem><ToggleGroupItem value="light">Light</ToggleGroupItem><ToggleGroupItem value="dark">Dark</ToggleGroupItem></ToggleGroup></div></section><section><h3>AI provider</h3><div className="setting-row"><div><b>Inference mode</b><p>Product-managed gateway or a key stored only in macOS Keychain.</p></div><select><option>Practice AI Gateway</option><option>OpenAI (BYOK)</option><option>OpenRouter (BYOK)</option><option>LiteLLM</option></select></div></section><section><h3>Execution safety</h3><div className="setting-row"><div><b>Per-run timeout</b><p>Applies to tests and program execution.</p></div><select><option>8 seconds</option><option>15 seconds</option><option>20 seconds</option></select></div><div className="setting-row"><div><b>Workspace access</b><p>Generated code is restricted to account-specific session workspaces.</p></div><span className="locked">Enforced</span></div></section><section><h3>Accessibility</h3><div className="setting-row"><div><b>Reduce motion</b><p>Also follows the macOS system preference.</p></div><button className="toggle" aria-label="Reduce motion"><span/></button></div></section></div>; }

function NewSession({ onClose, onCreate }: { onClose():void; onCreate(goal:string):void }) { const [goal,setGoal]=useState(""); return <Dialog open onOpenChange={(open)=>{if(!open)onClose()}}><DialogContent className="max-w-lg" from="bottom"><DialogHeader><span className="modal-icon"><Brain weight="duotone"/></span><DialogTitle>What do you want to get better at?</DialogTitle><DialogDescription>Start broad. The Training Agent will inspect your history before deciding what evidence to gather.</DialogDescription></DialogHeader><FieldGroup className="gap-3"><Field><FieldLabel htmlFor="session-goal" className="sr-only">Learning goal</FieldLabel><Textarea id="session-goal" autoFocus value={goal} onChange={e=>setGoal(e.target.value)} placeholder="I want to learn DSA deeply…"/></Field><div className="flex flex-wrap gap-2">{["Master TypeScript internals","Get better at system design","Deepen C++ problem solving"].map(v=><Button key={v} variant="outline" size="xs" onClick={()=>setGoal(v)}>{v}</Button>)}</div></FieldGroup><DialogFooter className="items-center sm:justify-between"><span className="flex items-center gap-2 text-xs text-muted-foreground"><SparklesIcon/>Uses your full learning history</span><Button disabled={goal.trim().length<3} onClick={()=>onCreate(goal.trim())}>Investigate and start<ArrowRightIcon data-icon="inline-end"/></Button></DialogFooter></DialogContent></Dialog>; }

function CommandPalette({ onClose, onPage }: { onClose():void; onPage(p:Page):void }) { const commands: Array<[string,Page,typeof HouseIcon]> = [["Go to Home","home",HouseIcon],["Browse Sessions","sessions",LayoutGridIcon],["Open Ability Map","ability",NetworkIcon],["Open History","history",HistoryIcon],["Open Settings","settings",SettingsIcon]]; return <Dialog open onOpenChange={(open)=>{if(!open)onClose()}}><DialogContent className="top-1/3 max-w-xl overflow-hidden p-0" showCloseButton={false} from="top"><DialogHeader className="sr-only"><DialogTitle>Command Palette</DialogTitle><DialogDescription>Search sessions, abilities, and navigation commands.</DialogDescription></DialogHeader><CommandRoot><CommandInput autoFocus placeholder="Search sessions, abilities, or commands…"/><CommandList><CommandEmpty>No matching command.</CommandEmpty><CommandGroup heading="Commands">{commands.map(([label,page,Icon])=><CommandItem key={page} onSelect={()=>onPage(page)}><Icon/>{label}<CommandShortcut>↵</CommandShortcut></CommandItem>)}</CommandGroup></CommandList></CommandRoot></DialogContent></Dialog>; }

function SectionHeader({title,action}:{title:string;action?:string}) { return <div className="section-header"><h2>{title}</h2>{action&&<button>{action}<CaretRight/></button>}</div>; }
function Movement({title,status,detail,tone}:{title:string;status:string;detail:string;tone:string}) { return <div className="movement"><span className={tone}/><div><b>{title}</b><small>{detail}</small></div><strong>{status}</strong><CaretRight/></div>; }
function HistoryRow({icon,title:label,session,status,time}:{icon:string;title:string;session:string;status:string;time:string}) { return <button className="history-row"><span className="language-icon">{icon}</span><div><b>{label}</b><small>{session}</small></div><span className="history-status"><Check/>{status}</span><time>{time}</time><CaretRight/></button>; }
function title(value:string){return value.charAt(0).toUpperCase()+value.slice(1)}
function formatDuration(seconds:number){const h=Math.floor(seconds/3600);const m=Math.floor((seconds%3600)/60);return h?`${h}h ${m}m`:`${m}m`}
