import { useMemo,useState } from "react";
import { ArrowRight,CheckCircle2,History,Search,XCircle } from "lucide-react";
import type { ChallengeHistorySummary,SessionSummary } from "@spar/domain";
import { cn } from "@/lib/utils";
import { relativeTime } from "@/lib/format";
import { EmptyState } from "../common/EmptyState";
import { LanguageGlyph,LANGUAGE_LABEL } from "../common/LanguageGlyph";

type Filter="all"|"passed"|"open"|"replaced";
const FILTERS:Array<{id:Filter;label:string}>=[{id:"all",label:"All"},{id:"open",label:"Open"},{id:"passed",label:"Passed"},{id:"replaced",label:"Replaced"}];

export function ChallengesPage({challenges,sessions,onOpen}:{challenges:ChallengeHistorySummary[];sessions:SessionSummary[];onOpen(session:SessionSummary):void}){
  const [filter,setFilter]=useState<Filter>("all");const [query,setQuery]=useState("");
  const visible=useMemo(()=>{const needle=query.trim().toLowerCase();return challenges.filter((item)=>{if(filter==="open"&&item.status!=="active")return false;if(filter==="passed"&&item.lastOutcome!=="passed")return false;if(filter==="replaced"&&!item.replacedByQuestionId)return false;return !needle||`${item.title} ${item.sessionTitle} ${item.language} ${item.difficulty}`.toLowerCase().includes(needle);});},[challenges,filter,query]);
  const open=(item:ChallengeHistorySummary)=>{const session=sessions.find((candidate)=>candidate.id===item.sessionId);if(session)onOpen(session);};
  return <div className="app-scroll h-full overflow-y-auto"><div className="mx-auto w-full max-w-[58rem] px-6 pb-16 pt-8">
    <h1 className="text-[1.35rem] font-semibold tracking-[-0.03em]">Challenges</h1>
    <p className="mt-1 text-content text-muted-foreground">Every generated challenge, attempt, test run, submission, and adaptive replacement stays in your account history.</p>
    <div className="mt-5 flex items-center gap-2"><div className="inline-flex rounded-lg border border-border bg-[var(--color-background-elevated-secondary)] p-0.5">{FILTERS.map((item)=><button key={item.id} className={cn("h-6 rounded-md px-2.5 text-ui transition-colors",filter===item.id?"bg-card text-foreground shadow-[var(--app-shadow-card)]":"text-muted-foreground hover:text-foreground")} onClick={()=>setFilter(item.id)} type="button">{item.label}</button>)}</div><div className="relative ml-auto w-60"><Search className="pointer-events-none absolute left-2 top-1/2 size-3.5 -translate-y-1/2 text-muted-foreground"/><input className="h-7 w-full rounded-lg border border-border bg-card pl-7 pr-2 text-ui outline-none placeholder:text-muted-foreground/70 focus-visible:border-[var(--border-strong)]" onChange={(event)=>setQuery(event.target.value)} placeholder="Filter challenge history" value={query}/></div></div>
    <div className="mt-4 flex flex-col gap-2">{visible.length?visible.map((item)=><button key={item.id} className="group rounded-xl border border-border bg-card px-4 py-3 text-left shadow-[var(--app-shadow-soft)] transition-colors hover:bg-accent/35" onClick={()=>open(item)} type="button"><div className="flex items-start gap-3"><span className="mt-0.5 grid size-8 shrink-0 place-items-center rounded-lg bg-[var(--color-background-elevated-secondary)] text-foreground/70" title={LANGUAGE_LABEL[item.language]}><LanguageGlyph className="size-4" language={item.language}/></span><span className="min-w-0 flex-1"><span className="flex items-center gap-2"><span className="truncate text-content font-semibold">{item.title}</span><span className="rounded-md border border-border px-1.5 py-0.5 text-ui-sm text-muted-foreground">{item.difficulty}</span>{item.lastOutcome==="passed"?<CheckCircle2 className="size-3.5 text-[var(--success)]"/>:item.lastOutcome==="failed"?<XCircle className="size-3.5 text-destructive"/>:null}</span><span className="mt-0.5 block text-ui text-muted-foreground">{item.sessionTitle} · {item.testRunCount} test run{item.testRunCount===1?"":"s"} · {item.attemptCount} attempt{item.attemptCount===1?"":"s"}</span>{item.replacesQuestionTitle&&<span className="mt-1 inline-flex items-center gap-1 text-ui-sm text-muted-foreground">Replaced <strong className="font-medium text-foreground/80">{item.replacesQuestionTitle}</strong></span>}{item.replacedByQuestionTitle&&<span className="mt-1 inline-flex items-center gap-1 text-ui-sm text-muted-foreground"><strong className="font-medium text-foreground/80">{item.replacedByQuestionTitle}</strong><ArrowRight className="size-3"/>became the next version</span>}</span><span className="shrink-0 text-ui-sm text-muted-foreground/70">{relativeTime(item.updatedAt)}</span></div></button>):<EmptyState icon={History} title={challenges.length?"Nothing matches this filter":"No challenges yet"} description={challenges.length?"Clear the filters to see the rest of your challenge history.":"A challenge appears here as soon as Spar compiles and validates it."}/>}</div>
  </div></div>;
}
