import { randomUUID } from "node:crypto";
import type { FastifyInstance } from "fastify";
import { and, desc, eq, sql } from "drizzle-orm";
import { appendEventsRequestSchema, sessionCheckpointSchema } from "@pracai/domain";
import { attemptEvents, attempts, sessionCheckpoints, sessions } from "@pracai/database";
import type { Database } from "@pracai/database";
import { requireUser } from "./auth.js";
import type { ObjectStorage } from "./storage.js";

export function installRoutes(app: FastifyInstance, db: Database, storage?: ObjectStorage) {
  app.get("/health", async () => ({ ok: true }));
  app.get("/v1/sessions", async (request) => { const user=await requireUser(request); return db.select().from(sessions).where(eq(sessions.userId,user.id)).orderBy(desc(sessions.updatedAt)); });
  app.post("/v1/sessions", async (request,reply) => { const user=await requireUser(request); const body=request.body as {id?:unknown;goal?:unknown;title?:unknown};const goal=String(body.goal??"").trim(); if(goal.length<3)return reply.code(400).send({error:"Goal is required"}); const supplied=typeof body.id==="string"&&/^[0-9a-f-]{36}$/i.test(body.id)?body.id:null;const id=supplied??randomUUID(); await db.insert(sessions).values({id,userId:user.id,title:String(body.title??goal).slice(0,80),originalGoal:goal}).onConflictDoNothing(); return reply.code(201).send({id}); });
  app.get("/v1/sessions/:id/checkpoints/latest", async (request,reply)=>{const user=await requireUser(request);const id=String((request.params as {id:string}).id);const row=await db.select().from(sessionCheckpoints).where(and(eq(sessionCheckpoints.sessionId,id),eq(sessionCheckpoints.userId,user.id))).orderBy(desc(sessionCheckpoints.version)).limit(1);return row[0]?.payload??reply.code(404).send({error:"Checkpoint not found"});});
  app.put("/v1/sessions/:id/checkpoints/:version", async(request,reply)=>{const user=await requireUser(request);const checkpoint=sessionCheckpointSchema.parse(request.body);const id=String((request.params as {id:string}).id);if(checkpoint.sessionId!==id)return reply.code(400).send({error:"Session mismatch"});const owned=await db.select({id:sessions.id}).from(sessions).where(and(eq(sessions.id,id),eq(sessions.userId,user.id))).limit(1);if(!owned[0])return reply.code(404).send({error:"Session not found"});await db.insert(sessionCheckpoints).values({id:checkpoint.id,sessionId:id,userId:user.id,version:checkpoint.version,eventSequence:checkpoint.eventSequence,payload:checkpoint}).onConflictDoNothing();return reply.code(204).send();});
  app.post("/v1/attempts/:id/events", async(request,reply)=>{const user=await requireUser(request);const value=appendEventsRequestSchema.parse(request.body);const attempt=await db.select().from(attempts).where(and(eq(attempts.id,value.attemptId),eq(attempts.userId,user.id))).limit(1);if(!attempt[0])return reply.code(404).send({error:"Attempt not found"});if(value.expectedSequence!==attempt[0].latestEventSequence+1)return reply.code(409).send({error:"Event sequence conflict",latestSequence:attempt[0].latestEventSequence});await db.transaction(async(tx)=>{await tx.insert(attemptEvents).values(value.events.map(e=>({id:e.id,attemptId:e.attemptId,sequence:e.sequence,type:e.type,source:e.source,payload:e.payload,schemaVersion:e.schemaVersion,occurredAt:new Date(e.occurredAt)}))).onConflictDoNothing();await tx.update(attempts).set({latestEventSequence:value.events.at(-1)!.sequence,updatedAt:new Date()}).where(eq(attempts.id,value.attemptId));});return reply.code(202).send({acceptedThrough:value.events.at(-1)!.sequence});});
  app.post("/v1/storage/upload",async(request,reply)=>{const user=await requireUser(request);if(!storage)return reply.code(503).send({error:"Object storage unavailable"});const body=request.body as {kind?:string;id?:string;contentType?:string};if(!["workspace","challenge"].includes(String(body.kind))||!body.id)return reply.code(400).send({error:"Invalid artifact"});const key=`users/${user.id}/${body.kind}/${body.id}`;return{key,url:await storage.uploadUrl(key,body.contentType)};});
}
