import { describe,expect,it } from "vitest";
import { randomUUID } from "node:crypto";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { LocalStore } from "./store.js";
import type { QuestionDesign } from "@spar/domain";

const design=(title:string):QuestionDesign=>({title,language:"javascript",kind:"function",statement:"Implement the target behavior while preserving the declared invariant through every transition.",starterFiles:{"src/index.js":"export function solve(){ throw new Error(\"implement\") }"},referenceFiles:{"src/index.js":"export function solve(){ return true }"},visibleTests:{"tests/visible.test.js":"// visible"},hiddenTests:{"tests/hidden.test.js":"// hidden"},knownIncorrectFiles:[{"src/index.js":"export function solve(){ return false }"}],runCommand:"node --test",accidentalDifficulty:[],expectedFailureSignatures:["returns before restoring the invariant"]});

it("persists the device theme across store reloads",()=>{const directory=mkdtempSync(path.join(tmpdir(),"spar-theme-"));const database=path.join(directory,"state.sqlite3");try{const first=new LocalStore(database);first.setSetting("theme","dark");first.close();const reopened=new LocalStore(database);try{expect(reopened.getSetting("theme","system")).toBe("dark");}finally{reopened.close();}}finally{rmSync(directory,{recursive:true,force:true});}});

it("clears learner data without erasing device preferences",()=>{const store=new LocalStore(":memory:");try{store.setSetting("theme","dark");const {sessionId}=store.createSession("Practise JavaScript arrays");store.setTrainingTarget(sessionId,{ability:"Arrays",specificGap:"Filter values",desiredEvidence:"Uses filter",avoidTesting:[]});store.createQuestion(sessionId,design("Filter values"),{valid:true});store.clearAccountData();expect(store.listSessions()).toEqual([]);expect(store.listAbilities()).toEqual([]);expect(store.getSetting("theme","system")).toBe("dark");}finally{store.close();}});

it("keeps the onboarding profile out of the next account",()=>{const store=new LocalStore(":memory:");try{const profile={name:"Abhinav",experience:"working" as const,focus:["Async and concurrency"],weakness:"I never know what needs awaiting.",language:"typescript" as const,completedAt:new Date().toISOString()};store.saveProfile(profile);expect(store.getProfile()).toEqual(profile);store.setPreferredLanguage("cpp");expect(store.getProfile()?.language).toBe("cpp");
  // Sign-out wipes account state, and the profile is account state: leaving it
  // behind would skip onboarding for whoever signs in next, on their predecessor's answers.
  store.clearAccountData();expect(store.getProfile()).toBeNull();}finally{store.close();}});

describe("local learning state",()=>{it("persists an evidence-bearing two-question adaptive chain",()=>{const store=new LocalStore(":memory:");try{const {sessionId}=store.createSession("Learn invariant-driven algorithms deeply");store.setObjective(sessionId,"Distinguish recognizing an invariant from restoring it repeatedly.");const first=store.setTrainingTarget(sessionId,{ability:"Invariant restoration",specificGap:"Repeated restoration after one mutation",desiredEvidence:"Uses a loop until validity returns",avoidTesting:["parsing"]});const q1=store.createQuestion(sessionId,design("Restore the window"),{valid:true});store.appendEvent({id:randomUUID(),attemptId:q1.attemptId,sequence:1,type:"learner_remark",occurredAt:new Date().toISOString(),payload:{body:"I know the invariant but I only repaired it once."},source:"learner",schemaVersion:1});store.updateAbility({abilityId:first.abilityId,markdown:"# Invariant restoration\n\nRecognizes the invariant; repeated restoration remains uncertain.",evidenceEventIds:[]});store.completeAttempt(q1.attemptId,"passed");store.setTrainingTarget(sessionId,{ability:"Invariant restoration",specificGap:"Transfer repeated restoration to an event stream",desiredEvidence:"Restores validity independently in a new representation",avoidTesting:["advanced syntax"]});store.createQuestion(sessionId,design("Repair the event stream"),{valid:true});const detail=store.readSession(sessionId);expect(detail?.summary.questionTitles).toHaveLength(2);expect(detail?.summary.completedQuestions).toBe(1);expect(detail?.question?.title).toBe("Repair the event stream");expect(store.readAbility(first.abilityId)).toMatchObject({version:1,status:"developing"});expect(store.readAttempt(q1.attemptId)).toEqual(expect.arrayContaining([expect.objectContaining({type:"learner_remark"})]));}finally{store.close();}});});

it("durably pauses an evidence-empty session for placement",()=>{const store=new LocalStore(":memory:");try{const{sessionId}=store.createSession("Understand the Node.js event loop");expect(store.hasLearnerEvidence()).toBe(false);const intake={questions:[{header:"Experience",question:"How comfortable are you with callbacks and Promises?",options:[{label:"New",description:"I have not used them."},{label:"Some",description:"I have seen them in small programs."}],multiple:false,custom:true}]};store.setPendingIntake(sessionId,intake);expect(store.readSession(sessionId)?.pendingLearnerQuestion?.questions[0]?.question).toContain("Promises");store.answerIntake(sessionId,"I have not used Promises yet.");expect(store.readSession(sessionId)?.pendingLearnerQuestion).toBeNull();expect(store.answeredIntake(sessionId)).toBe("I have not used Promises yet.");expect(store.setPendingIntake(sessionId,intake).status).toBe("answered");expect(store.readSession(sessionId)?.pendingLearnerQuestion).toBeNull();const target=store.setTrainingTarget(sessionId,{ability:"Function-call sequencing",specificGap:"Follow ordinary calls before asynchronous scheduling",desiredEvidence:"Predicts direct calls",avoidTesting:["Promises","timers"]});store.createQuestion(sessionId,{...design("Trace direct calls"),difficulty:"foundation"},{valid:true});const detail=store.readSession(sessionId);expect(detail?.question?.difficulty).toBe("foundation");expect(detail?.question?.abilityId).toBe(target.abilityId);}finally{store.close();}});

it("allocates live attempt sequences inside the authoritative transaction",()=>{const store=new LocalStore(":memory:");try{const{sessionId}=store.createSession("Practise JavaScript");store.setTrainingTarget(sessionId,{ability:"Control flow",specificGap:"Trace branches",desiredEvidence:"Explains the selected branch",avoidTesting:[]});const question=store.createQuestion(sessionId,design("Trace a branch"),{valid:true});const base={attemptId:question.attemptId,occurredAt:new Date().toISOString(),source:"learner" as const,schemaVersion:1 as const};const first=store.appendNextEvent({...base,id:randomUUID(),type:"file_changed",payload:{path:"src/index.js"}});const second=store.appendNextEvent({...base,id:randomUUID(),type:"learner_remark",payload:{body:"I expect the first branch."}});expect([first.sequence,second.sequence]).toEqual([1,2]);expect(store.readSession(sessionId)?.question?.latestEventSequence).toBe(2);expect(store.readAttempt(question.attemptId)).toEqual(expect.arrayContaining([expect.objectContaining({sequence:1,type:"file_changed"}),expect.objectContaining({sequence:2,type:"learner_remark"})]));}finally{store.close();}});

it("does not treat unrelated history as evidence for a new goal",()=>{const store=new LocalStore(":memory:");try{const{sessionId}=store.createSession("Practise interval scheduling");const target=store.setTrainingTarget(sessionId,{ability:"Greedy interval scheduling",specificGap:"Endpoint compatibility",desiredEvidence:"Selects a maximum compatible sequence",avoidTesting:[]});store.updateAbility({abilityId:target.abilityId,markdown:"# Greedy interval scheduling\n\nSelects intervals by earliest finish time.",evidenceEventIds:[]});expect(store.hasRelevantLearnerEvidence("greedy interval scheduling interview")).toBe(true);expect(store.hasRelevantLearnerEvidence("prepare for an AI engineer interview in five days")).toBe(false);}finally{store.close();}});

it("makes an unconsumed training target idempotent",()=>{const store=new LocalStore(":memory:");try{const{sessionId}=store.createSession("Learn model evaluation");const input={ability:"Model evaluation",specificGap:"Separate ranking from calibration",desiredEvidence:"Chooses the metric matching the decision",avoidTesting:["framework syntax"]};const first=store.setTrainingTarget(sessionId,input);const second=store.setTrainingTarget(sessionId,input);expect(second.id).toBe(first.id);expect(store.readSession(sessionId)?.summary.currentFocus).toEqual(["Model evaluation"]);}finally{store.close();}});

it("rolls back an incomplete planning draft without touching messages",()=>{const store=new LocalStore(":memory:");try{const{sessionId}=store.createSession("Prepare for an AI engineer interview");store.addMessage(sessionId,"learner","I have five days.");store.setObjective(sessionId,"Draft objective that never reached a playable question");store.setTrainingTarget(sessionId,{ability:"Unrelated stale target",specificGap:"Draft gap",desiredEvidence:"Draft evidence",avoidTesting:[]});expect(store.resetIncompletePlanning(sessionId)).toBe(true);const detail=store.readSession(sessionId);expect(detail?.summary.objective).toBe("Investigating your prior evidence and defining the first training target.");expect(detail?.summary.currentFocus).toEqual([]);expect(detail?.messages).toHaveLength(1);expect(store.latestTarget(sessionId)).toBeUndefined();}finally{store.close();}});

it("preserves challenge test history and links an adaptive replacement",()=>{const store=new LocalStore(":memory:");try{const{sessionId}=store.createSession("Practise loops");store.setTrainingTarget(sessionId,{ability:"Loop control",specificGap:"Count matching values",desiredEvidence:"Uses one direct loop",avoidTesting:[]});const first=store.createQuestion(sessionId,design("Count values"),{valid:true});store.appendNextEvent({id:randomUUID(),attemptId:first.attemptId,type:"test_run",occurredAt:new Date().toISOString(),payload:{scope:"visible",passed:false,exitCode:1},source:"runner",schemaVersion:1});store.setTrainingTarget(sessionId,{ability:"Loop control",specificGap:"Count positive values",desiredEvidence:"Uses one condition inside a loop",avoidTesting:[]});const second=store.replaceQuestion(sessionId,design("Count positive values"),{valid:true},"The first challenge was too difficult.");const history=store.listChallenges();expect(second.ordinal).toBe(2);expect(history).toEqual(expect.arrayContaining([expect.objectContaining({id:first.id,testRunCount:1,replacedByQuestionId:second.id,lastOutcome:"replaced"}),expect.objectContaining({id:second.id,replacesQuestionId:first.id})]));expect(store.readChallenge(first.id)).toMatchObject({design:{title:"Count values"},attempts:[{events:expect.arrayContaining([expect.objectContaining({type:"test_run"})])}]});}finally{store.close();}});

it("files a session away without disturbing what was last worked on",()=>{const store=new LocalStore(":memory:");try{const first=store.createSession("Practise dynamic programming");store.createSession("Practise graph traversal");const before=store.listSessions().map((session)=>session.updatedAt).sort();store.renameSession(first.sessionId,"  Dynamic programming  ");store.setSessionPinned(first.sessionId,true);const listed=store.listSessions();
  // Pinned to the top, renamed, and every last-touched time exactly as it was:
  // tidying the list is not work on the goal, and bumping it would shuffle what
  // the learner just organized straight back down.
  expect(listed[0]).toMatchObject({id:first.sessionId,title:"Dynamic programming"});expect(listed.map((session)=>session.updatedAt).sort()).toEqual(before);
  store.setSessionArchived(first.sessionId,true);expect(store.listSessions().find((session)=>session.id===first.sessionId)).toMatchObject({pinnedAt:null,archivedAt:expect.any(String)});
  store.setSessionArchived(first.sessionId,false);expect(store.listSessions().find((session)=>session.id===first.sessionId)?.archivedAt).toBeNull();
  expect(store.pendingSync().map((item)=>item.kind)).toContain("session-rename");}finally{store.close();}});

it("takes a deleted session's evidence with it and keeps the ability it taught",()=>{const store=new LocalStore(":memory:");try{const{sessionId}=store.createSession("Practise recursion");const target=store.setTrainingTarget(sessionId,{ability:"Recursion",specificGap:"Base cases",desiredEvidence:"States the base case before recurring",avoidTesting:[]});const question=store.createQuestion(sessionId,design("Sum a tree"),{valid:true});store.updateAbility({abilityId:target.abilityId,markdown:"# Recursion\n\nStates the base case before recurring.",evidenceEventIds:[]});store.addMessage(sessionId,"learner","Where should I start?");expect(store.deleteSession(sessionId)).toBe(true);expect(store.listSessions()).toEqual([]);expect(store.readSession(sessionId)).toBeNull();expect(store.readAttempt(question.attemptId)).toEqual([]);expect(store.listChallenges()).toEqual([]);
  // What Spar learned about the learner is not the session's to take with it.
  expect(store.listAbilities()).toHaveLength(1);expect(store.pendingSync().map((item)=>item.kind)).toContain("session-delete");
  // A turn that outlived the row it was writing for, and a second delete of the
  // same session, both have to be survivable rather than throwing.
  expect(store.addMessage(sessionId,"agent","An answer that arrived too late")).toBeNull();expect(store.deleteSession(sessionId)).toBe(false);}finally{store.close();}});
