import { sql } from "drizzle-orm";
import { bigint, boolean, index, integer, jsonb, pgEnum, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid, vector } from "drizzle-orm/pg-core";

const timestamps = { createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() };
export const sessionStatus = pgEnum("session_status", ["planning", "active", "paused", "completed"]);
export const questionStatus = pgEnum("question_status", ["generating", "validating", "playable", "active", "completed", "invalid"]);
export const attemptStatus = pgEnum("attempt_status", ["active", "paused", "completed"]);

export const users = pgTable("users", { id: uuid("id").primaryKey().defaultRandom(), email: text("email").notNull(), passwordHash: text("password_hash"), displayName: text("display_name"), avatarUrl: text("avatar_url"), ...timestamps }, (t) => [uniqueIndex("users_email_idx").on(t.email)]);
export const authAccounts = pgTable("auth_accounts", { userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), provider: text("provider").notNull(), providerAccountId: text("provider_account_id").notNull(), ...timestamps }, (t) => [primaryKey({ columns: [t.provider, t.providerAccountId] }), index("auth_accounts_user_idx").on(t.userId)]);
export const userSettings = pgTable("user_settings", { userId: uuid("user_id").primaryKey().references(() => users.id, { onDelete: "cascade" }), settings: jsonb("settings").$type<Record<string, unknown>>().notNull().default({}), ...timestamps });

export const sessions = pgTable("sessions", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), title: text("title").notNull(), originalGoal: text("original_goal").notNull(), objective: text("objective").notNull().default(""), status: sessionStatus("status").notNull().default("planning"), totalSeconds: integer("total_seconds").notNull().default(0), ...timestamps }, (t) => [index("sessions_user_updated_idx").on(t.userId, t.updatedAt)]);
export const trainingTargets = pgTable("training_targets", { id: uuid("id").primaryKey().defaultRandom(), sessionId: uuid("session_id").notNull().references(() => sessions.id, { onDelete: "cascade" }), abilityDocumentId: uuid("ability_document_id"), action: text("action").notNull(), specificGap: text("specific_gap").notNull(), desiredEvidence: text("desired_evidence").notNull(), avoidTesting: jsonb("avoid_testing").$type<string[]>().notNull().default([]), ...timestamps });
export const questions = pgTable("questions", { id: uuid("id").primaryKey().defaultRandom(), sessionId: uuid("session_id").notNull().references(() => sessions.id, { onDelete: "cascade" }), trainingTargetId: uuid("training_target_id").notNull().references(() => trainingTargets.id), ordinal: integer("ordinal").notNull(), title: text("title").notNull(), statement: text("statement").notNull(), language: text("language").notNull(), kind: text("kind").notNull(), difficulty: text("difficulty").notNull(), status: questionStatus("status").notNull().default("generating"), challengeArtifactId: uuid("challenge_artifact_id"), engineVersion: text("engine_version").notNull(), ...timestamps }, (t) => [uniqueIndex("questions_session_ordinal_idx").on(t.sessionId, t.ordinal)]);
export const challengeArtifacts = pgTable("challenge_artifacts", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id), objectKey: text("object_key").notNull(), contentHash: text("content_hash").notNull(), manifest: jsonb("manifest").$type<Record<string, unknown>>().notNull(), validatedAt: timestamp("validated_at", { withTimezone: true }), validationReport: jsonb("validation_report"), ...timestamps }, (t) => [uniqueIndex("challenge_artifact_hash_idx").on(t.userId, t.contentHash)]);

export const attempts = pgTable("attempts", { id: uuid("id").primaryKey().defaultRandom(), questionId: uuid("question_id").notNull().references(() => questions.id), userId: uuid("user_id").notNull().references(() => users.id), status: attemptStatus("status").notNull().default("active"), latestEventSequence: integer("latest_event_sequence").notNull().default(-1), startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(), completedAt: timestamp("completed_at", { withTimezone: true }), ...timestamps }, (t) => [index("attempts_user_updated_idx").on(t.userId, t.updatedAt)]);
export const attemptEvents = pgTable("attempt_events", { id: uuid("id").primaryKey(), attemptId: uuid("attempt_id").notNull().references(() => attempts.id, { onDelete: "cascade" }), sequence: integer("sequence").notNull(), type: text("type").notNull(), source: text("source").notNull(), payload: jsonb("payload").$type<Record<string, unknown>>().notNull(), schemaVersion: integer("schema_version").notNull().default(1), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull() }, (t) => [uniqueIndex("attempt_events_sequence_idx").on(t.attemptId, t.sequence)]);
export const learnerRemarks = pgTable("learner_remarks", { id: uuid("id").primaryKey().defaultRandom(), attemptId: uuid("attempt_id").notNull().references(() => attempts.id, { onDelete: "cascade" }), eventId: uuid("event_id").notNull().references(() => attemptEvents.id), body: text("body").notNull(), ...timestamps });
export const attemptTraces = pgTable("attempt_traces", { id: uuid("id").primaryKey().defaultRandom(), attemptId: uuid("attempt_id").notNull().references(() => attempts.id, { onDelete: "cascade" }), version: integer("version").notNull(), markdown: text("markdown").notNull(), supersededAt: timestamp("superseded_at", { withTimezone: true }), ...timestamps }, (t) => [uniqueIndex("attempt_traces_version_idx").on(t.attemptId, t.version)]);

export const conceptNodes = pgTable("concept_nodes", { id: uuid("id").primaryKey().defaultRandom(), slug: text("slug").notNull().unique(), title: text("title").notNull(), description: text("description").notNull(), failureSignatures: jsonb("failure_signatures").$type<string[]>().notNull().default([]), ...timestamps });
export const conceptRelations = pgTable("concept_relations", { fromId: uuid("from_id").notNull().references(() => conceptNodes.id), toId: uuid("to_id").notNull().references(() => conceptNodes.id), kind: text("kind").notNull() }, (t) => [primaryKey({ columns: [t.fromId, t.toId, t.kind] })]);
export const abilityDocuments = pgTable("ability_documents", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), conceptId: uuid("concept_id").notNull().references(() => conceptNodes.id), status: text("status").notNull(), currentVersion: integer("current_version").notNull().default(1), searchText: text("search_text").notNull().default(""), embedding: vector("embedding", { dimensions: 1536 }), lastObservedAt: timestamp("last_observed_at", { withTimezone: true }), ...timestamps }, (t) => [uniqueIndex("ability_user_concept_idx").on(t.userId, t.conceptId)]);
export const abilityDocumentVersions = pgTable("ability_document_versions", { id: uuid("id").primaryKey().defaultRandom(), abilityDocumentId: uuid("ability_document_id").notNull().references(() => abilityDocuments.id, { onDelete: "cascade" }), version: integer("version").notNull(), markdown: text("markdown").notNull(), reason: text("reason").notNull(), createdByAgentRunId: uuid("created_by_agent_run_id"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("ability_versions_idx").on(t.abilityDocumentId, t.version)]);
export const abilityEvidenceLinks = pgTable("ability_evidence_links", { abilityDocumentVersionId: uuid("ability_document_version_id").notNull().references(() => abilityDocumentVersions.id, { onDelete: "cascade" }), attemptEventId: uuid("attempt_event_id").notNull().references(() => attemptEvents.id), description: text("description").notNull() }, (t) => [primaryKey({ columns: [t.abilityDocumentVersionId, t.attemptEventId] })]);

export const sessionCheckpoints = pgTable("session_checkpoints", { id: uuid("id").primaryKey(), sessionId: uuid("session_id").notNull().references(() => sessions.id, { onDelete: "cascade" }), userId: uuid("user_id").notNull().references(() => users.id), version: integer("version").notNull(), eventSequence: integer("event_sequence").notNull(), payload: jsonb("payload").$type<Record<string, unknown>>().notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("session_checkpoint_version_idx").on(t.sessionId, t.version)]);
export const workspaceSnapshots = pgTable("workspace_snapshots", { id: uuid("id").primaryKey(), userId: uuid("user_id").notNull().references(() => users.id), sessionId: uuid("session_id").notNull().references(() => sessions.id), objectKey: text("object_key").notNull(), contentHash: text("content_hash").notNull(), byteLength: bigint("byte_length", { mode: "number" }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const agentRuns = pgTable("agent_runs", { id: uuid("id").primaryKey(), userId: uuid("user_id").notNull().references(() => users.id), sessionId: uuid("session_id").notNull().references(() => sessions.id), attemptId: uuid("attempt_id").references(() => attempts.id), provider: text("provider").notNull(), model: text("model").notNull(), contextReferences: jsonb("context_references").$type<string[]>().notNull().default([]), toolTrace: jsonb("tool_trace").$type<unknown[]>().notNull().default([]), promptTokens: integer("prompt_tokens"), completionTokens: integer("completion_tokens"), estimatedCostMicros: bigint("estimated_cost_micros", { mode: "number" }), latencyMs: integer("latency_ms"), finalAction: text("final_action"), error: text("error"), startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(), completedAt: timestamp("completed_at", { withTimezone: true }) });

export const schemaHealth = pgTable("schema_health", { singleton: boolean("singleton").primaryKey().default(true), migrationVersion: integer("migration_version").notNull(), checkedAt: timestamp("checked_at", { withTimezone: true }).notNull().default(sql`now()`) });
