import { sql } from "drizzle-orm";
import { bigint, boolean, index, integer, jsonb, pgEnum, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid, vector } from "drizzle-orm/pg-core";

const timestamps = { createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() };
export const sessionStatus = pgEnum("session_status", ["planning", "active", "paused", "completed"]);
export const questionStatus = pgEnum("question_status", ["generating", "validating", "playable", "active", "completed", "invalid", "abandoned"]);
export const attemptStatus = pgEnum("attempt_status", ["active", "paused", "completed"]);

export const users = pgTable("users", { id: uuid("id").primaryKey().defaultRandom(), email: text("email").notNull(), emailVerified: boolean("email_verified").notNull().default(false), displayName: text("display_name"), avatarUrl: text("avatar_url"), ...timestamps }, (t) => [uniqueIndex("users_email_idx").on(t.email)]);
/* The three tables below are Better Auth's, mapped onto Spar's names in
   apps/api/src/auth.ts. They are declared here rather than left to Better Auth's
   own migrator so that one drizzle history owns every table in the database —
   two migration tools pointed at the same schema is how you end up with a
   staging database nobody can reproduce.

   `auth_accounts` holds the credential itself: Better Auth keeps a password on
   the account row rather than on the user, because an account is per-provider
   and a user can end up with a password and a Google sign-in side by side. */
export const authAccounts = pgTable("auth_accounts", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: text("account_id").notNull(), providerId: text("provider_id").notNull(), password: text("password"), accessToken: text("access_token"), refreshToken: text("refresh_token"), accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }), refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }), scope: text("scope"), idToken: text("id_token"), ...timestamps }, (t) => [uniqueIndex("auth_accounts_provider_idx").on(t.providerId, t.accountId), index("auth_accounts_user_idx").on(t.userId)]);
/** One signed-in device. The desktop app holds `token` in the OS keychain and
 *  sends it as a bearer token, so a session outliving the window is the point. */
export const authSessions = pgTable("auth_sessions", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), token: text("token").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), ipAddress: text("ip_address"), userAgent: text("user_agent"), ...timestamps }, (t) => [uniqueIndex("auth_sessions_token_idx").on(t.token), index("auth_sessions_user_idx").on(t.userId)]);
/** Short-lived one-time codes: email verification and password reset. Rows are
 *  consumed on use and expire on their own, so this table is always near-empty. */
export const authVerifications = pgTable("auth_verifications", { id: uuid("id").primaryKey().defaultRandom(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), ...timestamps }, (t) => [index("auth_verifications_identifier_idx").on(t.identifier)]);
export const userSettings = pgTable("user_settings", { userId: uuid("user_id").primaryKey().references(() => users.id, { onDelete: "cascade" }), settings: jsonb("settings").$type<Record<string, unknown>>().notNull().default({}), ...timestamps });

/* `pinnedAt`, `archivedAt` and `currentFocus` are the learner's own filing, not
   device preferences: a session pinned on a laptop is pinned because it matters,
   and it should still be at the top of the list on a desktop. */
export const sessions = pgTable("sessions", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), title: text("title").notNull(), originalGoal: text("original_goal").notNull(), objective: text("objective").notNull().default(""), status: sessionStatus("status").notNull().default("planning"), totalSeconds: integer("total_seconds").notNull().default(0), pinnedAt: timestamp("pinned_at", { withTimezone: true }), archivedAt: timestamp("archived_at", { withTimezone: true }), currentFocus: jsonb("current_focus").$type<string[]>().notNull().default([]), ...timestamps }, (t) => [index("sessions_user_updated_idx").on(t.userId, t.updatedAt)]);
export const trainingTargets = pgTable("training_targets", { id: uuid("id").primaryKey().defaultRandom(), sessionId: uuid("session_id").notNull().references(() => sessions.id, { onDelete: "cascade" }), abilityDocumentId: uuid("ability_document_id"), action: text("action").notNull(), specificGap: text("specific_gap").notNull(), desiredEvidence: text("desired_evidence").notNull(), avoidTesting: jsonb("avoid_testing").$type<string[]>().notNull().default([]), ...timestamps });
/* `sourceRef` is which problem at which judge this challenge came from, null for
   everything Spar wrote itself. `concepts` is what the challenge is about, as
   `[{slug, role}]` — carried on the row rather than through `conceptRelations`
   because it is a tag list the device reads back verbatim, and a challenge
   restored without its tags is invisible to every concept rollup. */
export const questions = pgTable("questions", { id: uuid("id").primaryKey().defaultRandom(), sessionId: uuid("session_id").notNull().references(() => sessions.id, { onDelete: "cascade" }), trainingTargetId: uuid("training_target_id").notNull().references(() => trainingTargets.id), ordinal: integer("ordinal").notNull(), title: text("title").notNull(), statement: text("statement").notNull(), language: text("language").notNull(), kind: text("kind").notNull(), difficulty: text("difficulty").notNull(), status: questionStatus("status").notNull().default("generating"), challengeArtifactId: uuid("challenge_artifact_id"), replacesQuestionId: uuid("replaces_question_id"), engineVersion: text("engine_version").notNull(), sourceRef: jsonb("source_ref").$type<Record<string, unknown>>(), concepts: jsonb("concepts").$type<Array<{ slug: string; role: string }>>().notNull().default([]), ...timestamps }, (t) => [uniqueIndex("questions_session_ordinal_idx").on(t.sessionId, t.ordinal),index("questions_replacement_idx").on(t.replacesQuestionId)]);
export const challengeArtifacts = pgTable("challenge_artifacts", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), objectKey: text("object_key").notNull(), contentHash: text("content_hash").notNull(), manifest: jsonb("manifest").$type<Record<string, unknown>>().notNull(), validatedAt: timestamp("validated_at", { withTimezone: true }), validationReport: jsonb("validation_report"), ...timestamps }, (t) => [uniqueIndex("challenge_artifact_hash_idx").on(t.userId, t.contentHash)]);

export const attempts = pgTable("attempts", { id: uuid("id").primaryKey().defaultRandom(), questionId: uuid("question_id").notNull().references(() => questions.id, { onDelete: "cascade" }), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), status: attemptStatus("status").notNull().default("active"), latestEventSequence: integer("latest_event_sequence").notNull().default(-1), startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(), completedAt: timestamp("completed_at", { withTimezone: true }), ...timestamps }, (t) => [index("attempts_user_updated_idx").on(t.userId, t.updatedAt)]);
export const attemptEvents = pgTable("attempt_events", { id: uuid("id").primaryKey(), attemptId: uuid("attempt_id").notNull().references(() => attempts.id, { onDelete: "cascade" }), sequence: integer("sequence").notNull(), type: text("type").notNull(), source: text("source").notNull(), payload: jsonb("payload").$type<Record<string, unknown>>().notNull(), schemaVersion: integer("schema_version").notNull().default(1), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull() }, (t) => [uniqueIndex("attempt_events_sequence_idx").on(t.attemptId, t.sequence)]);
export const learnerRemarks = pgTable("learner_remarks", { id: uuid("id").primaryKey().defaultRandom(), attemptId: uuid("attempt_id").notNull().references(() => attempts.id, { onDelete: "cascade" }), eventId: uuid("event_id").notNull().references(() => attemptEvents.id), body: text("body").notNull(), ...timestamps });
export const attemptTraces = pgTable("attempt_traces", { id: uuid("id").primaryKey().defaultRandom(), attemptId: uuid("attempt_id").notNull().references(() => attempts.id, { onDelete: "cascade" }), version: integer("version").notNull(), markdown: text("markdown").notNull(), supersededAt: timestamp("superseded_at", { withTimezone: true }), ...timestamps }, (t) => [uniqueIndex("attempt_traces_version_idx").on(t.attemptId, t.version)]);

export const conceptNodes = pgTable("concept_nodes", { id: uuid("id").primaryKey().defaultRandom(), slug: text("slug").notNull().unique(), title: text("title").notNull(), description: text("description").notNull(), failureSignatures: jsonb("failure_signatures").$type<string[]>().notNull().default([]), ...timestamps });
export const conceptRelations = pgTable("concept_relations", { fromId: uuid("from_id").notNull().references(() => conceptNodes.id), toId: uuid("to_id").notNull().references(() => conceptNodes.id), kind: text("kind").notNull() }, (t) => [primaryKey({ columns: [t.fromId, t.toId, t.kind] })]);
/* An ability is something the learner can be told they have, so it carries its
   own one-line claim, the drills for going deeper, and when evidence first
   supported it — the same fields the device holds.

   `conceptId` is nullable now. It used to be required, which forced the write
   path to invent a throwaway `concept_nodes` row per ability just to have
   something to point at; `conceptSlugs` carries the real tags instead. The
   column stays for abilities that do name a node in the shipped taxonomy. */
export const abilityDocuments = pgTable("ability_documents", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), conceptId: uuid("concept_id").references(() => conceptNodes.id), title: text("title").notNull().default(""), summary: text("summary").notNull().default(""), practice: jsonb("practice").$type<string[]>().notNull().default([]), earnedAt: timestamp("earned_at", { withTimezone: true }), conceptSlugs: jsonb("concept_slugs").$type<string[]>().notNull().default([]), status: text("status").notNull(), currentVersion: integer("current_version").notNull().default(1), searchText: text("search_text").notNull().default(""), embedding: vector("embedding", { dimensions: 1536 }), lastObservedAt: timestamp("last_observed_at", { withTimezone: true }), ...timestamps }, (t) => [uniqueIndex("ability_user_concept_idx").on(t.userId, t.conceptId)]);
export const abilityDocumentVersions = pgTable("ability_document_versions", { id: uuid("id").primaryKey().defaultRandom(), abilityDocumentId: uuid("ability_document_id").notNull().references(() => abilityDocuments.id, { onDelete: "cascade" }), version: integer("version").notNull(), markdown: text("markdown").notNull(), reason: text("reason").notNull(), createdByAgentRunId: uuid("created_by_agent_run_id"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("ability_versions_idx").on(t.abilityDocumentId, t.version)]);
export const abilityEvidenceLinks = pgTable("ability_evidence_links", { abilityDocumentVersionId: uuid("ability_document_version_id").notNull().references(() => abilityDocumentVersions.id, { onDelete: "cascade" }), attemptEventId: uuid("attempt_event_id").notNull().references(() => attemptEvents.id), description: text("description").notNull() }, (t) => [primaryKey({ columns: [t.abilityDocumentVersionId, t.attemptEventId] })]);

/** The conversation. Everything else in this schema is what Spar concluded; this
 *  is what was actually said, and a learner signing in on another machine to
 *  find their sessions stripped of the thread would rightly call that amnesia.
 *  `activity` is the tool steps the turn took, kept with the reply they produced. */
export const agentMessages = pgTable("agent_messages", { id: uuid("id").primaryKey(), sessionId: uuid("session_id").notNull().references(() => sessions.id, { onDelete: "cascade" }), role: text("role").notNull(), body: text("body").notNull(), activity: jsonb("activity").$type<unknown[]>().notNull().default([]), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [index("agent_messages_session_idx").on(t.sessionId, t.createdAt)]);

/** Concepts the agent invented for one learner. The shipped taxonomy is in the
 *  binary and reseeds itself on any device, so only these are worth carrying —
 *  and they are per-learner by construction, which is why this is not
 *  `concept_nodes`. */
export const learnerConcepts = pgTable("learner_concepts", { userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), slug: text("slug").notNull(), title: text("title").notNull(), kind: text("kind").notNull(), parentSlug: text("parent_slug"), description: text("description").notNull().default(""), ...timestamps }, (t) => [primaryKey({ columns: [t.userId, t.slug] })]);

export const sessionCheckpoints = pgTable("session_checkpoints", { id: uuid("id").primaryKey(), sessionId: uuid("session_id").notNull().references(() => sessions.id, { onDelete: "cascade" }), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), version: integer("version").notNull(), eventSequence: integer("event_sequence").notNull(), payload: jsonb("payload").$type<Record<string, unknown>>().notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("session_checkpoint_version_idx").on(t.sessionId, t.version)]);
export const workspaceSnapshots = pgTable("workspace_snapshots", { id: uuid("id").primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), sessionId: uuid("session_id").notNull().references(() => sessions.id, { onDelete: "cascade" }), objectKey: text("object_key").notNull(), contentHash: text("content_hash").notNull(), byteLength: bigint("byte_length", { mode: "number" }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const agentRuns = pgTable("agent_runs", { id: uuid("id").primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), sessionId: uuid("session_id").notNull().references(() => sessions.id, { onDelete: "cascade" }), attemptId: uuid("attempt_id").references(() => attempts.id, { onDelete: "cascade" }), provider: text("provider").notNull(), model: text("model").notNull(), contextReferences: jsonb("context_references").$type<string[]>().notNull().default([]), toolTrace: jsonb("tool_trace").$type<unknown[]>().notNull().default([]), promptTokens: integer("prompt_tokens"), completionTokens: integer("completion_tokens"), estimatedCostMicros: bigint("estimated_cost_micros", { mode: "number" }), latencyMs: integer("latency_ms"), finalAction: text("final_action"), error: text("error"), startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(), completedAt: timestamp("completed_at", { withTimezone: true }) });

export const schemaHealth = pgTable("schema_health", { singleton: boolean("singleton").primaryKey().default(true), migrationVersion: integer("migration_version").notNull(), checkedAt: timestamp("checked_at", { withTimezone: true }).notNull().default(sql`now()`) });
